service: random-image

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:List*"
      Resource: "arn:aws:s3:::lambda-random-image"

plugins:
 - serverless-apigw-binary

custom:
  apigwBinary:
    types: ['image/jpeg']

functions:
  main:
    handler: handler.main
    description: Return image file randomly on specified bucket
    events:
      - http:
          method: get
          path: image
          integration: lambda_proxy

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lambda-random-image
        AccessControl : PublicRead
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
    Cloudfront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            TargetOriginId: LambdaRandomImage
            ViewerProtocolPolicy: allow-all
            ForwardedValues:
              QueryString: true
            MinTTL: 0
            MaxTTL: 60
            DefaultTTL: 60
          Enabled: true
          Origins:
            - Id: LambdaRandomImage
              DomainName:
                Fn::Join:
                  - ""
                  - [ { Ref: "ApiGatewayRestApi" }, ".execute-api.ap-northeast-1.amazonaws.com" ]
              OriginPath: "/dev/image"
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
              OriginCustomHeaders:
                - HeaderName: Accept
                  HeaderValue: image/jpeg

  Outputs:
     S3Bucket:
       Description: "Randomly select image from this bucket"
       Value: { Ref: S3Bucket }
