service: random-image

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

functions:
  main:
    handler: handler.main
    events:
      - http:
          method: get
          path: image
          integration: lambda
          response:
            headers:
              Content-Type: "'text/html'"
              Location: integration.response.body.location
            template: $input.path('$')
            statusCodes:
              302:
                pattern: ''

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lambda-random-image
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
