service: random-image

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:List*"
      Resource: "arn:aws:s3:::lambda-random-image"

functions:
  main:
    handler: handler.main
    events:
      - http:
          method: get
          path: image
          integration: lambda_proxy
          response:
            headers:
              Content-Type: "'image/jpeg'"
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ''

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: lambda-random-image
        AccessControl : PublicRead
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
